medium/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :whats
  resources :comments
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

medium/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

medium/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :idea
end

medium/app/models/post.rb
class Post < ApplicationRecord
end

medium/app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
         gravtastic
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        end

medium/app/models/what.rb
class What < ApplicationRecord
    has_many :comments
end

medium/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

medium/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :idea_id)
    end
end

medium/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

medium/app/controllers/whats_controller.rb
class WhatsController < ApplicationController
  before_action :set_what, only: [:show, :edit, :update, :destroy]

  # GET /whats
  # GET /whats.json
  def index
    @whats = What.all
  end

  # GET /whats/1
  # GET /whats/1.json
  def show
  end

  # GET /whats/new
  def new
    @what = What.new
  end

  # GET /whats/1/edit
  def edit
  end
  @comments = @idea.comments.all
  @comment = @idea.comments.build
  # POST /whats
  # POST /whats.json
  def create
    @what = What.new(what_params)

    respond_to do |format|
      if @what.save
        format.html { redirect_to @what, notice: 'What was successfully created.' }
        format.json { render :show, status: :created, location: @what }
      else
        format.html { render :new }
        format.json { render json: @what.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /whats/1
  # PATCH/PUT /whats/1.json
  def update
    respond_to do |format|
      if @what.update(what_params)
        format.html { redirect_to @what, notice: 'What was successfully updated.' }
        format.json { render :show, status: :ok, location: @what }
      else
        format.html { render :edit }
        format.json { render json: @what.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /whats/1
  # DELETE /whats/1.json
  def destroy
    @what.destroy
    respond_to do |format|
      format.html { redirect_to whats_url, notice: 'What was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_what
      @what = What.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def what_params
      params.require(:what).permit(:user_name, :body, :idea_id)
    end
end

medium/app/helpers/application_helper.rb
module ApplicationHelper
end

medium/app/helpers/comments_helper.rb
module CommentsHelper
end

medium/app/helpers/posts_helper.rb
module PostsHelper
end

medium/app/helpers/whats_helper.rb
module WhatsHelper
end

medium/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Medium</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href=" https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

      <body>
        <div class="container">
        <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
        <%= yield %>
        </div>
        <p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<%= image_tag current_user.gravatar_url, :class => "gravatar" %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
      </body>
</html>

medium/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

medium/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

medium/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<div class="container">
  <div class="row">
  <% @posts.each do |post| %>
    <div class="col-sm-4">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= post.title %></h5>
          <p class="card-text"><%= truncate(post.content,:length => 80) %></p>
          <%= link_to 'Show', post %>
          <%= link_to 'Edit', edit_post_path(post) %>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
      </div>
    <% end %>
    <br>
  </div>
</div>

<%= link_to 'New Post', new_post_path %>

medium/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

medium/app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

medium/app/views/whats/_form.html.erb
<%= form_with(model: what, local: true) do |form| %>
  <% if what.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(what.errors.count, "error") %> prohibited this what from being saved:</h2>

      <ul>
        <% what.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
<%= form.hidden_field :idea_id %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

medium/app/views/whats/edit.html.erb
<h1>Editing What</h1>

<%= render 'form', what: @what %>

<%= link_to 'Show', @what %> |
<%= link_to 'Back', whats_path %>

medium/app/views/whats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Whats</h1>

<table class="table">
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Idea</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @whats.each do |what| %>
      <tr>
        <td><%= what.user_name %></td>
        <td><%= what.body %></td>
        <td><%= what.idea_id %></td>
        <td><%= link_to 'Show', what %></td>
        <td><%= link_to 'Edit', edit_what_path(what) %></td>
        <td><%= link_to 'Destroy', what, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New What', new_what_path %>

medium/app/views/whats/new.html.erb
<h1>New What</h1>

<%= render 'form', what: @what %>

<%= link_to 'Back', whats_path %>

medium/app/views/whats/show.html.erb
<p>
  <strong>User name:</strong>
  <%= @what.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @what.body %>
</p>

<p>
  <strong>Idea:</strong>
  <%= @what.idea_id %>
</p>
<%= image_tag(@idea.picture_url, :width => 600) if @idea.picture.present? %>
<h3>Comments</h3>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user_name %></strong>
    <br>
    <p><%= comment.body %></p>
    <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
<% end %>
<%= render partial: 'comments/form', locals: { comment: @comment } %>

<%= link_to 'Edit', edit_what_path(@what) %> |
<%= link_to 'Back', whats_path %>